package view;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import model.Mensalidade;
import model.Cliente;
import model.Acesso;
import model.Endereco;

/**
 *
 * @author vinicius
 */

public class IFrmCliente extends javax.swing.JInternalFrame {
    ArrayList<Cliente> cliente;
    ArrayList<Endereco> endereco;
    ArrayList<Mensalidade> mensalidade;
    Cliente c;
    private DefaultTableModel dtm;
    Endereco e = new Endereco();
    Acesso a = new Acesso();
    Session s;
    private int escolha;
    
    /**
     * Creates new form IFrmCliente
     * @param s
     */
    
    public IFrmCliente(Session s) {
        initComponents();
        this.s = s;
        dtm = (DefaultTableModel)tblCliente.getModel();        
        popularCombo();
        popularTabela();
        label();
        escolha = -1;
    }
    
    public void label(){
        Mensalidade m = (Mensalidade) cbxMensalidade.getSelectedItem();
        lbValor.setText("R$: " + m.getValor());
    }
    
    public void popularCombo(){
        mensalidade = (ArrayList<Mensalidade>) s.createQuery("From Mensalidade").list();
        for(Mensalidade m : mensalidade){
            cbxMensalidade.addItem(m);
        }        
        
    }
    
    public void popularTabela(){ 
        cliente = (ArrayList<Cliente>) s.createQuery("From Cliente").list();
        dtm.setRowCount(0);        
        for(Cliente cl : cliente){
            dtm.addRow(cl.toRow()); 
        } 
    }
    
    private void atualizarTabela(Cliente c, int codigo){
        if (codigo == -1){
            dtm.addRow(c.toRow());
            
        }
        else{
            dtm.removeRow(codigo); 
            dtm.insertRow(codigo, c.toRow());
        }
    }
    
    public boolean campoVazio(){
        if(fTextCep.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (CEP)!");
            return false;
        }
        if(txtNumero.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (Número)!");
            return false;
        }
        if(txtLogradouro.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (Logradouro)!");
            return false;
        }
        if(txtBairro.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (Bairro)!");
            return false;
        }
        if(fTextCpf.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (CPF)!");
            return false;
        }
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (Nome)!");
            return false;
        }
        if(txtTelefone.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (Telefone)!");
            return false;
        }
        if((int)spnDiaVencimento.getValue() == 0){
            JOptionPane.showMessageDialog(this, "Campo obrigatório vazio (Dia de vencimento da mensalidade)!");
            return false;
        }
        
        return true;
    }
    
    public void limparCampos(){
        fTextCep.setText("");
        txtNumero.setText("");
        txtLogradouro.setText("");
        txtBairro.setText("");
        fTextCpf.setText("");
        txtNome.setText("");
        txtObjetivo.setToolTipText("");
        txtTelefone.setText("");
        cbxSexo.setSelectedIndex(0);
        txtEmail.setText("");
        cbxStatus.setSelectedIndex(0);
        spnDiaVencimento.setValue(1);
        txtObjetivo.append("");
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        fTextCpf = new javax.swing.JFormattedTextField();
        btnBuscar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        cbxSexo = new javax.swing.JComboBox<>();
        txtEmail = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtTelefone = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        spnDiaVencimento = new javax.swing.JSpinner();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        fTextCep = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        txtLogradouro = new javax.swing.JTextField();
        txtNumero = new javax.swing.JTextField();
        txtBairro = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        cbxStatus = new javax.swing.JComboBox<>();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObjetivo = new javax.swing.JTextArea();
        jLabel14 = new javax.swing.JLabel();
        cbxMensalidade = new javax.swing.JComboBox<>();
        jLabel15 = new javax.swing.JLabel();
        lbValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblCliente = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cadastrar Cliente");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel1.setText("*CPF :");

        try {
            fTextCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        jLabel2.setText("*Nome :");

        jLabel3.setText("Sexo :");

        jLabel4.setText("E-mail :");

        cbxSexo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "F" }));

        jLabel5.setText("*Telefone :");

        jLabel6.setText("Dia de vencimento da mensalidade: ");

        spnDiaVencimento.setModel(new javax.swing.SpinnerNumberModel(1, 1, 31, 1));

        jLabel7.setText("Objetivo :");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Endereço", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel8.setText("*CEP :");

        try {
            fTextCep.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("#####-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel9.setText("*Número :");

        jLabel10.setText("*Bairro :");

        jLabel11.setText("*Logradouro :");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(fTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNumero))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addGap(18, 18, 18)
                                .addComponent(txtBairro))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, 225, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(fTextCep, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(txtNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txtLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txtBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jLabel12.setText("Status :");

        cbxStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ativo", "Inativo" }));

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel13.setText("Todos os campos com (*) são obrigatórios!");

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        txtObjetivo.setColumns(20);
        txtObjetivo.setRows(5);
        jScrollPane2.setViewportView(txtObjetivo);

        jLabel14.setText("Mesalidade:");

        cbxMensalidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbxMensalidadeActionPerformed(evt);
            }
        });

        jLabel15.setText("VALOR :");

        lbValor.setText("R$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(fTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnBuscar)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel6)
                        .addGap(18, 18, 18)
                        .addComponent(spnDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel12)
                        .addGap(18, 18, 18)
                        .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel7)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(10, 10, 10)
                                        .addComponent(jScrollPane2)
                                        .addGap(35, 35, 35)))
                                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(77, 77, 77))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(18, 18, 18)
                                .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel4)
                                .addGap(18, 18, 18)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(221, 221, 221)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(cbxMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(lbValor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnCadastrar)
                                .addGap(18, 18, 18)
                                .addComponent(btnEditar)
                                .addGap(18, 18, 18)
                                .addComponent(btnLimparCampos)
                                .addGap(18, 18, 18)
                                .addComponent(btnSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(fTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(spnDiaVencimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(cbxStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(cbxSexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 3, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel14)
                                    .addComponent(cbxMensalidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel15)
                                    .addComponent(lbValor))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel13)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnEditar)
                                    .addComponent(btnLimparCampos)
                                    .addComponent(btnCadastrar)
                                    .addComponent(btnSelecionar)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        tblCliente.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "Nome", "Telefone", "Sexo", "E-mail", "Status", "Dia de vencimento", "Mensalidade", "Objetivo", "CEP", "Número", "Logradouro", "Bairro"
            }
        ));
        jScrollPane1.setViewportView(tblCliente);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(4, 4, 4)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 191, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        String m = cbxSexo.getSelectedItem().toString();
        Mensalidade men = (Mensalidade)cbxMensalidade.getSelectedItem();
        char sexo = m.charAt(0); 
        if(campoVazio()){
            a = new Acesso(fTextCpf.getText(),
                            "",
                            3);
                    
            e = new Endereco(fTextCep.getText(),
                             txtNumero.getText(),
                             txtLogradouro.getText(),
                             txtBairro.getText());  

            c = new Cliente(fTextCpf.getText(),
                            e,
                            men,
                            txtNome.getText(),
                            txtTelefone.getText(),
                            sexo,
                            txtEmail.getText(),
                            cbxStatus.getSelectedItem().toString(),
                            (int)spnDiaVencimento.getValue(),
                            txtObjetivo.getToolTipText());
            try{   
                s.beginTransaction();
                s.save(a);
                s.save(e);
                s.save(c);
                s.getTransaction().commit();
                JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
                atualizarTabela(c, escolha);
                limparCampos();
            }catch(Exception ex){
                JOptionPane.showMessageDialog(this, ex);
            }
        }   
            
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       /* int esc = tblCliente.getSelectedRow();
        String m = cbxSexo.getSelectedItem().toString();
        char sexo = m.charAt(0); 
        if(esc == -1){
            JOptionPane.showMessageDialog(this, "Escolha um valor da tabela! Depois clique em selecionar!",
                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }else{
            if(campoVazio()){
                cliente = cliente = (ArrayList<Cliente>) s.createQuery("From Cliente").list();        
                for(Cliente cl : cliente){
                    if(cl.getCpfCliente().equals(fTextCpf.getText())){
                        endereco = endereco = (ArrayList<Endereco>) s.createQuery("From Endereco").list();
                        for(Endereco en : endereco){
                            if(en.getCep().equals(fTextCep.getText())){
                                en.setCep(fTextCep.getText());
                                en.setNumero(txtNumero.getText());
                                en.setLogradouro(txtLogradouro.getText());
                                en.setBairro(txtBairro.getText());

                                cl.setCpfCliente(fTextCpf.getText());
                                cl.setEndereco(e);
                                cl.setNomeCliente(txtNome.getText());
                                cl.setTelefone(txtTelefone.getText());
                                cl.setSexo(sexo);
                                cl.setEmail(txtEmail.getText());
                                cl.setStatus(cbxStatus.getSelectedItem().toString());
                                cl.setDiaVencimento((int)spnDiaVencimento.getValue());
                                cl.setObjetivo(txtObjetivo.getText());
                                cl.setEndereco(en);

                                try{ 
                                    s.beginTransaction();
                                    s.update(en);
                                    s.update(cl);
                                    s.getTransaction().commit();
                                    JOptionPane.showMessageDialog(this, "Edição realizada com sucesso!");
                                    atualizarTabela(cl, esc);
                                    limparCampos();
                                }catch(Exception ex){
                                    JOptionPane.showMessageDialog(this, ex);
                                }
                            }                            
                        }
                            
                    }
                }
                
            }
            
        }*/
    }//GEN-LAST:event_btnEditarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int esc = tblCliente.getSelectedRow();

        if(esc == -1){
            JOptionPane.showMessageDialog(this, "Escolha um valor da tabela!",
                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }else{
            fTextCpf.setText(tblCliente.getValueAt(esc, 0).toString());
            txtNome.setText(tblCliente.getValueAt(esc, 1).toString());
            txtTelefone.setText(tblCliente.getValueAt(esc, 2).toString());
            cbxSexo.setSelectedItem(tblCliente.getValueAt(esc, 3).toString());
            txtEmail.setText(tblCliente.getValueAt(esc, 4).toString());
            cbxStatus.setSelectedItem(tblCliente.getValueAt(esc, 5).toString());
            spnDiaVencimento.setValue(Integer.parseInt(tblCliente.getValueAt(esc, 6).toString()));
            cbxMensalidade.setSelectedItem((Mensalidade)tblCliente.getValueAt(esc, 7));
            txtObjetivo.append((String) tblCliente.getValueAt(esc, 8));
            fTextCep.setText(tblCliente.getValueAt(esc, 9).toString());
            txtNumero.setText(tblCliente.getValueAt(esc, 10).toString());
            txtLogradouro.setText(tblCliente.getValueAt(esc, 11).toString());
            txtBairro.setText(tblCliente.getValueAt(esc, 12).toString());           
        }
    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        cliente = cliente = (ArrayList<Cliente>) s.createQuery("From Cliente").list();        
        int cont = 0;
        dtm.setRowCount(0);
        for(Cliente cl : cliente){
            if(cl.getCpfCliente().equals(fTextCpf.getText())){
                dtm.addRow(cl.toRow());
                cont = 1;
            }
        }
        if(cont == 0){
            popularTabela();
            JOptionPane.showMessageDialog(this, "CPF não cadastrado!",
                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void cbxMensalidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbxMensalidadeActionPerformed
        Mensalidade m = (Mensalidade) cbxMensalidade.getSelectedItem();
        lbValor.setText("R$: " + m.getValor());        
    }//GEN-LAST:event_cbxMensalidadeActionPerformed

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JComboBox<Object> cbxMensalidade;
    private javax.swing.JComboBox<String> cbxSexo;
    private javax.swing.JComboBox<String> cbxStatus;
    private javax.swing.JFormattedTextField fTextCep;
    private javax.swing.JFormattedTextField fTextCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbValor;
    private javax.swing.JSpinner spnDiaVencimento;
    private javax.swing.JTable tblCliente;
    private javax.swing.JTextField txtBairro;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtLogradouro;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNumero;
    private javax.swing.JTextArea txtObjetivo;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
