package view;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.Session;
import model.Personal;
import model.Acesso;
/**
 *
 * @author vinicius
 */
public class IFrmPersonal extends javax.swing.JInternalFrame {
    Session s;
    Acesso a;
    Personal p;
    ArrayList<Personal> personal;
    private DefaultTableModel dtm;
    private int escolha;
    /**
     * Creates new form IFrmPersonal
     * @param s
     */
    public IFrmPersonal(Session s) {
        initComponents();
        this.s = s;
        dtm = (DefaultTableModel)tblPersonal.getModel();
        popularTabela();
        escolha = -1;
    }
    
    public boolean campoVazio(){
        if(fTextCpf.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo CPF!");
            return false;
        }
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo nome!");
            return false;
        }
        if(txtTurno.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Preencha o campo turno!");
           return false; 
        }
        if(txtSenha.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Preencha o campo senha!");
           return false; 
        }
        
        return true;
    }
    
    public boolean campoVazioEditar(){
        if(fTextCpf.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo CPF!");
            return false;
        }
        if(txtNome.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Preencha o campo nome!");
            return false;
        }
        if(txtTurno.getText().equals("")){
           JOptionPane.showMessageDialog(this, "Preencha o campo turno!");
           return false; 
        }
        return true;
    }
    
    
    
    public boolean cpfValido(){
        Personal pCPF = new Personal();
        boolean cpfValidado = pCPF.validaCPF(fTextCpf.getText().replaceAll("[^0-9]", ""));
                
        return cpfValidado;
    }
    
    
    
    
    public void limparCampos(){
        fTextCpf.setText("");
        txtNome.setText("");
        txtTurno.setText("");
        txtSenha.setText("");
        txtConfSenha.setText("");
    }
    
    private void popularTabela(){ 
        personal = (ArrayList<Personal>) s.createQuery("From Personal").list();
        dtm.setRowCount(0);        
        for(Personal pe : personal){
            dtm.addRow(pe.toRow()); 
        } 
    }
    private void atualizarTabela(Personal p, int codigo){
        if (codigo == -1){
            dtm.addRow(p.toRow());
            
        }
        else{
            dtm.removeRow(codigo); 
            dtm.insertRow(codigo, p.toRow());
        }
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnCadastrar = new javax.swing.JButton();
        btnEditar = new javax.swing.JButton();
        btnLimparCampos = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        fTextCpf = new javax.swing.JFormattedTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtTurno = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtSenha = new javax.swing.JPasswordField();
        txtConfSenha = new javax.swing.JPasswordField();
        jLabel5 = new javax.swing.JLabel();
        btnSelecionar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblPersonal = new javax.swing.JTable();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.HIDE_ON_CLOSE);
        setTitle("Cadastro de Personal");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados do Personal", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        btnCadastrar.setText("Cadastrar");
        btnCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCadastrarActionPerformed(evt);
            }
        });

        btnEditar.setText("Editar");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        btnLimparCampos.setText("Limpar Campos");
        btnLimparCampos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparCamposActionPerformed(evt);
            }
        });

        jLabel1.setText("CPF :");

        try {
            fTextCpf.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel2.setText("Nome :");

        jLabel3.setText("Turno :");

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Senha de acesso", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Arial", 0, 12))); // NOI18N

        jLabel4.setText("Senha:");

        jLabel5.setText("Confirmar senha:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(0, 61, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(txtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtConfSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        btnSelecionar.setText("Selecionar");
        btnSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelecionarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtTurno, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addComponent(jLabel2)
                        .addComponent(txtNome, javax.swing.GroupLayout.DEFAULT_SIZE, 201, Short.MAX_VALUE)
                        .addComponent(fTextCpf))
                    .addComponent(jLabel3))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(80, 80, 80))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addComponent(btnCadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEditar)
                        .addGap(18, 18, 18)
                        .addComponent(btnLimparCampos)
                        .addGap(18, 18, 18)
                        .addComponent(btnSelecionar)
                        .addContainerGap(29, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditar)
                            .addComponent(btnLimparCampos)
                            .addComponent(btnCadastrar)
                            .addComponent(btnSelecionar)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)
                        .addGap(1, 1, 1)
                        .addComponent(fTextCpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTurno, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(16, Short.MAX_VALUE))
        );

        tblPersonal.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "CPF", "NOME", "TURNO"
            }
        ));
        jScrollPane1.setViewportView(tblPersonal);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 121, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparCamposActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparCamposActionPerformed
        limparCampos();
    }//GEN-LAST:event_btnLimparCamposActionPerformed

    private void btnCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCadastrarActionPerformed
        personal = (ArrayList<Personal>) s.createQuery("From Personal").list();
        int conf = 0;
        for(Personal p1 : personal){
            if(p1.getCpfPersonal().equals(fTextCpf.getText())){
                JOptionPane.showMessageDialog(this, "CPF já está cadastrado!");
                conf = 1;
            }
        }
        if(conf == 0){
            if(campoVazio()){
                if(cpfValido()){
                    if(txtSenha.getText().equals(txtConfSenha.getText())){
                       a = new Acesso(fTextCpf.getText(),
                                    txtSenha.getText(),
                                    2);

                        p = new Personal(fTextCpf.getText(),
                                         txtNome.getText(),
                                         txtTurno.getText());
                        try{  
                            s.beginTransaction();
                            s.save(a);
                            s.save(p);
                            s.getTransaction().commit();
                            JOptionPane.showMessageDialog(this, "Cadastro realizado com sucesso!");
                            atualizarTabela(p, escolha);
                            limparCampos();
                        }catch(Exception ex){
                            JOptionPane.showMessageDialog(this, ex);
                        } 
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "CPF Invalido!");
                }
                
            }
        }
            
            
        
    }//GEN-LAST:event_btnCadastrarActionPerformed

    private void btnSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelecionarActionPerformed
        int esc =tblPersonal.getSelectedRow();

        if(esc == -1){
            JOptionPane.showMessageDialog(this, "Escolha um valor da tabela!",
                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }else{
            
            fTextCpf.setText(tblPersonal.getValueAt(esc, 0).toString());
            txtNome.setText(tblPersonal.getValueAt(esc, 1).toString());
            txtTurno.setText(tblPersonal.getValueAt(esc, 2).toString());
            
        }

    }//GEN-LAST:event_btnSelecionarActionPerformed

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
       int esc = tblPersonal.getSelectedRow();
       
        if(esc == -1){
            JOptionPane.showMessageDialog(this, "Escolha um valor da tabela! Depois clique em selecionar!",
                "ATENÇÃO", JOptionPane.WARNING_MESSAGE);
        }else{
            if(campoVazioEditar()){
                personal = personal = (ArrayList<Personal>) s.createQuery("From Personal").list();        
                for(Personal pr : personal){
                    if(pr.getCpfPersonal().equals(fTextCpf.getText())){
               
                                pr.setCpfPersonal(fTextCpf.getText());
                                pr.setNomePersonal(txtNome.getText());
                                pr.setTurno(txtTurno.getText());

                                try{ 
                                    s.beginTransaction();
                                   
                                    s.update(pr);
                                    s.getTransaction().commit();
                                    JOptionPane.showMessageDialog(this, "Edição realizada com sucesso!");
                                    atualizarTabela(pr, esc);
                                    limparCampos();
                                }catch(Exception ex){
                                    JOptionPane.showMessageDialog(this, ex);
                                }
                    
                }
                
            }
            
        }
            
        }
    }//GEN-LAST:event_btnEditarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCadastrar;
    private javax.swing.JButton btnEditar;
    private javax.swing.JButton btnLimparCampos;
    private javax.swing.JButton btnSelecionar;
    private javax.swing.JFormattedTextField fTextCpf;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblPersonal;
    private javax.swing.JPasswordField txtConfSenha;
    private javax.swing.JTextField txtNome;
    private javax.swing.JPasswordField txtSenha;
    private javax.swing.JTextField txtTurno;
    // End of variables declaration//GEN-END:variables
}
