package model;
// Generated 31/08/2021 16:33:37 by Hibernate Tools 4.3.1



/**
 * Acesso generated by hbm2java
 */
public class Acesso  implements java.io.Serializable {


     private String cpfUsuario;
     private String senha;
     private int nivel;

    public Acesso() {
    }

    public Acesso(String cpfUsuario, String senha, int nivel) {
       this.cpfUsuario = cpfUsuario;
       this.senha = senha;
       this.nivel = nivel;
    }
   
    public String getCpfUsuario() {
        return this.cpfUsuario;
    }
    
    public void setCpfUsuario(String cpfUsuario) {
        this.cpfUsuario = cpfUsuario;
    }
    public String getSenha() {
        return this.senha;
    }
    
    public void setSenha(String senha) {
        this.senha = senha;
    }
    public int getNivel() {
        return this.nivel;
    }
    
    public void setNivel(int nivel) {
        this.nivel = nivel;
    }




}


