package model;
// Generated 31/08/2021 16:33:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import br.com.caelum.stella.validation.CPFValidator;

/**
 * Cliente generated by hbm2java
 */
public class Cliente  implements java.io.Serializable {


     private String cpfCliente;
     private Endereco endereco;
     private Mensalidade mensalidade;
     private String nomeCliente;
     private String telefone;
     private char sexo;
     private String email;
     private String status;
     private int diaVencimento;
     private String objetivo;
     private Set pagamentos = new HashSet(0);
     private Set planoTreinos = new HashSet(0);

    public Cliente() {
    }

	
    public Cliente(String cpfCliente, Endereco endereco, Mensalidade mensalidade, String nomeCliente, String telefone, char sexo, String email, String status, int diaVencimento, String objetivo) {
        this.cpfCliente = cpfCliente;
        this.endereco = endereco;
        this.mensalidade = mensalidade;
        this.nomeCliente = nomeCliente;
        this.telefone = telefone;
        this.sexo = sexo;
        this.email = email;
        this.status = status;
        this.diaVencimento = diaVencimento;
        this.objetivo = objetivo;
    }
    public Cliente(String cpfCliente, Endereco endereco, Mensalidade mensalidade, String nomeCliente, String telefone, char sexo, String email, String status, int diaVencimento, String objetivo, Set pagamentos, Set planoTreinos) {
       this.cpfCliente = cpfCliente;
       this.endereco = endereco;
       this.mensalidade = mensalidade;
       this.nomeCliente = nomeCliente;
       this.telefone = telefone;
       this.sexo = sexo;
       this.email = email;
       this.status = status;
       this.diaVencimento = diaVencimento;
       this.objetivo = objetivo;
       this.pagamentos = pagamentos;
       this.planoTreinos = planoTreinos;
    }
   
    public String getCpfCliente() {
        return this.cpfCliente;
    }
    
    public void setCpfCliente(String cpfCliente) {
        this.cpfCliente = cpfCliente;
    }
    public Endereco getEndereco() {
        return this.endereco;
    }
    
    public void setEndereco(Endereco endereco) {
        this.endereco = endereco;
    }
    public Mensalidade getMensalidade() {
        return this.mensalidade;
    }
    
    public void setMensalidade(Mensalidade mensalidade) {
        this.mensalidade = mensalidade;
    }
    public String getNomeCliente() {
        return this.nomeCliente;
    }
    
    public void setNomeCliente(String nomeCliente) {
        this.nomeCliente = nomeCliente;
    }
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }
    public char getSexo() {
        return this.sexo;
    }
    
    public void setSexo(char sexo) {
        this.sexo = sexo;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getStatus() {
        return this.status;
    }
    
    public void setStatus(String status) {
        this.status = status;
    }
    public int getDiaVencimento() {
        return this.diaVencimento;
    }
    
    public void setDiaVencimento(int diaVencimento) {
        this.diaVencimento = diaVencimento;
    }
    public String getObjetivo() {
        return this.objetivo;
    }
    
    public void setObjetivo(String objetivo) {
        this.objetivo = objetivo;
    }
    public Set getPagamentos() {
        return this.pagamentos;
    }
    
    public void setPagamentos(Set pagamentos) {
        this.pagamentos = pagamentos;
    }
    public Set getPlanoTreinos() {
        return this.planoTreinos;
    }
    
    public void setPlanoTreinos(Set planoTreinos) {
        this.planoTreinos = planoTreinos;
    }

    public String[] toRow(){
   
         return new String[]{
            String.valueOf(cpfCliente),
            nomeCliente,
            telefone,
            String.valueOf(sexo),
            email,
            status,
            String.valueOf(diaVencimento),
            mensalidade.getNomeMensalidade(),
            objetivo,
            String.valueOf(endereco.getCep()),
            endereco.getNumero(),
            endereco.getLogradouro(),
            endereco.getBairro()
      };
    }
    
    public boolean validaCPF(String cpf){
         CPFValidator cpfValidator = new CPFValidator();
         try {
            cpfValidator.assertValid(cpf);
            return true;
         }catch(Exception e){
            e.printStackTrace();
            return false;   
         }
    }
}


