package model;
// Generated 31/08/2021 16:33:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Endereco generated by hbm2java
 */
public class Endereco  implements java.io.Serializable {


     private String cep;
     private String numero;
     private String logradouro;
     private String bairro;
     private Set clientes = new HashSet(0);

    public Endereco() {
    }

	
    public Endereco(String cep, String numero, String logradouro, String bairro) {
        this.cep = cep;
        this.numero = numero;
        this.logradouro = logradouro;
        this.bairro = bairro;
    }
    public Endereco(String cep, String numero, String logradouro, String bairro, Set clientes) {
       this.cep = cep;
       this.numero = numero;
       this.logradouro = logradouro;
       this.bairro = bairro;
       this.clientes = clientes;
    }
   
    public String getCep() {
        return this.cep;
    }
    
    public void setCep(String cep) {
        this.cep = cep;
    }
    public String getNumero() {
        return this.numero;
    }
    
    public void setNumero(String numero) {
        this.numero = numero;
    }
    public String getLogradouro() {
        return this.logradouro;
    }
    
    public void setLogradouro(String logradouro) {
        this.logradouro = logradouro;
    }
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }




}


