package model;
// Generated 31/08/2021 16:33:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Exercicio generated by hbm2java
 */
public class Exercicio  implements java.io.Serializable {


     private Integer idExercicio;
     private String nomeExercicio;
     private int qtdSeries;
     private int qtdRepeticoes;
     private String observacao;
     private Set planoTreinos = new HashSet(0);

    public Exercicio() {
    }

	
    public Exercicio(String nomeExercicio, int qtdSeries, int qtdRepeticoes, String observacao) {
        this.nomeExercicio = nomeExercicio;
        this.qtdSeries = qtdSeries;
        this.qtdRepeticoes = qtdRepeticoes;
        this.observacao = observacao;
    }
    public Exercicio(String nomeExercicio, int qtdSeries, int qtdRepeticoes, String observacao, Set planoTreinos) {
       this.nomeExercicio = nomeExercicio;
       this.qtdSeries = qtdSeries;
       this.qtdRepeticoes = qtdRepeticoes;
       this.observacao = observacao;
       this.planoTreinos = planoTreinos;
    }
   
    public Integer getIdExercicio() {
        return this.idExercicio;
    }
    
    public void setIdExercicio(Integer idExercicio) {
        this.idExercicio = idExercicio;
    }
    public String getNomeExercicio() {
        return this.nomeExercicio;
    }
    
    public void setNomeExercicio(String nomeExercicio) {
        this.nomeExercicio = nomeExercicio;
    }
    public int getQtdSeries() {
        return this.qtdSeries;
    }
    
    public void setQtdSeries(int qtdSeries) {
        this.qtdSeries = qtdSeries;
    }
    public int getQtdRepeticoes() {
        return this.qtdRepeticoes;
    }
    
    public void setQtdRepeticoes(int qtdRepeticoes) {
        this.qtdRepeticoes = qtdRepeticoes;
    }
    public String getObservacao() {
        return this.observacao;
    }
    
    public void setObservacao(String observacao) {
        this.observacao = observacao;
    }
    public Set getPlanoTreinos() {
        return this.planoTreinos;
    }
    
    public void setPlanoTreinos(Set planoTreinos) {
        this.planoTreinos = planoTreinos;
    }




}


