package model;
// Generated 31/08/2021 16:33:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Mensalidade generated by hbm2java
 */
public class Mensalidade  implements java.io.Serializable {


     private Integer idMensalidade;
     private String nomeMensalidade;
     private float valor;
     private String tipo;
     private Set clientes = new HashSet(0);

    public Mensalidade() {
    }

	
    public Mensalidade(String nomeMensalidade, float valor, String tipo) {
        this.nomeMensalidade = nomeMensalidade;
        this.valor = valor;
        this.tipo = tipo;
    }
    public Mensalidade(String nomeMensalidade, float valor, String tipo, Set clientes) {
       this.nomeMensalidade = nomeMensalidade;
       this.valor = valor;
       this.tipo = tipo;
       this.clientes = clientes;
    }
   
    public Integer getIdMensalidade() {
        return this.idMensalidade;
    }
    
    public void setIdMensalidade(Integer idMensalidade) {
        this.idMensalidade = idMensalidade;
    }
    public String getNomeMensalidade() {
        return this.nomeMensalidade;
    }
    
    public void setNomeMensalidade(String nomeMensalidade) {
        this.nomeMensalidade = nomeMensalidade;
    }
    public float getValor() {
        return this.valor;
    }
    
    public void setValor(float valor) {
        this.valor = valor;
    }
    public String getTipo() {
        return this.tipo;
    }
    
    public void setTipo(String tipo) {
        this.tipo = tipo;
    }
    public Set getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set clientes) {
        this.clientes = clientes;
    }

    public String[] toRow(){
   
         return new String[]{
             String.valueOf(idMensalidade),
             nomeMensalidade,
             tipo,
             String.valueOf(valor)
             
      };
    }

    @Override
    public String toString() {
        return getNomeMensalidade(); //To change body of generated methods, choose Tools | Templates.
    }
    

}


