package model;
// Generated 31/08/2021 16:33:37 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Treino generated by hbm2java
 */
public class Treino  implements java.io.Serializable {


     private Integer idTreino;
     private String nomeTreino;
     private Set planoTreinos = new HashSet(0);

    public Treino() {
    }

	
    public Treino(String nomeTreino) {
        this.nomeTreino = nomeTreino;
    }
    public Treino(String nomeTreino, Set planoTreinos) {
       this.nomeTreino = nomeTreino;
       this.planoTreinos = planoTreinos;
    }
   
    public Integer getIdTreino() {
        return this.idTreino;
    }
    
    public void setIdTreino(Integer idTreino) {
        this.idTreino = idTreino;
    }
    public String getNomeTreino() {
        return this.nomeTreino;
    }
    
    public void setNomeTreino(String nomeTreino) {
        this.nomeTreino = nomeTreino;
    }
    public Set getPlanoTreinos() {
        return this.planoTreinos;
    }
    
    public void setPlanoTreinos(Set planoTreinos) {
        this.planoTreinos = planoTreinos;
    }




}


